FROM gcr.io/distroless/static@sha256:60a7d0c45932b6152b2f7ba561db2f91f58ab14aa90b895c58f72062c768fd77
MAINTAINER Marko Mikulicic <mkmik@vmware.com>
COPY controller /usr/local/bin/

EXPOSE 8080
ENTRYPOINT ["controller"]
